server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl.auto: update
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            redirectUri: ${OAUTH2_REDIRECT_URI}
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/youtube
              - https://www.googleapis.com/auth/youtube.readonly

auth:
  token-secret: ${TOKEN_SECRET}
  token-expiration: ${TOKEN_EXPIRATION}
  authorized-redirect-urls:
    - ${AUTHORIZED_REDIRECT_URL}