# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Grant execute permssion for gradlew 
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        OAUTH2_CLIENT_ID: ${{ secrets.OAUTH2_CLIENT_ID }}
        OAUTH2_CLIENT_SECRET: ${{ secrets.OAUTH2_CLIENT_SECERT }}
        OAUTH2_REDIRECT_URI: ${{ secrets.OAUTH2_REDIRECT_URI }}
        AUTHORIZED_REDIRECT_URL: ${{ secret.AUTHORIZED_REDIRECT_URL }}
        TOKEN_SECERT: ${{ secrets.TOKEN_SECERT }}
        TOKEN_EXPIRATION: ${{ secrets.TOKEN_EXPIRATION }}
      with:
        arguments: build
